# Setup
title: Brand Elements
url: https://brand.wire.com
baseurl: ""

highlighter: rouge
markdown: kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Exclude directories and/or files from the conversion. 
exclude: 
- Gemfile*
- Icon.png
- node_modules
- package.json
- README.md
- yarn.lock

# Custom vars
version: "1.0.0"
github:
  repo:  https://github.com/wireapp/brand
